### ISSUE TITLE
Uncaught Error: Call to undefined function ProcessWire\bd()

### ISSUE THREAD

**Issue by Alpine418** [flydev-fr/Duplicator#21]
I got the following error message in the php logs:

`[23-Mar-2022 15:23:37 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to undefined function ProcessWire\bd() in C:\foo\bar\site\modules\Duplicator\Duplicator.module:622
Stack trace:
#0 C:\foo\bar\wire\core\Wire.php(417): ProcessWire\Duplicator->___cronJob(Object(ProcessWire\HookEvent))
#1 C:\foo\bar\wire\core\WireHooks.php(951): ProcessWire\Wire->_callMethod('___cronJob', Array)
#2 C:\foo\bar\wire\core\Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Duplicator), 'cronJob', Array)
#3 C:\foo\bar\site\modules\Duplicator\Duplicator.module(289): ProcessWire\Wire->__call('cronJob', Array)
#4 C:\foo\bar\wire\core\Modules.php(682): ProcessWire\Duplicator->init()
#5 C:\foo\bar\wire\core\Modules.php(1448): ProcessWire\Modules->initModule(Object(ProcessWire\Duplicator), Array)
#6 C:\foo\bar\wire\core\Modules.php(1257): ProcessWire\Modules->getModule('Duplicator')
#7 C:\foo\bar in C:\foo\bar\site\modules\Duplicator\Duplicator.module on line 622`

**Comment by flydev-fr** [comment]
thanks @rjgamer missed to deleted this tracydebugger call

**Comment by flydev-fr** [comment]
done
