### ISSUE TITLE
Trying to access array offset on value of type bool in Duplicator.module:622

### ISSUE THREAD

**Issue by adrianbj** [flydev-fr/Duplicator#28]
Hi @flydev-fr - just had this for the first time. The line in question is: `if ($package && $package['zipfile'] !== null) {` 

Given that `buildPackage()` often returns `true` or `false`, the error makes sense.

Let me know if you need anything else.

Thanks!

**Comment by flydev-fr** [comment]
I just pushed a fix, will be merged in a minute. Thanks @adrianbj

**Comment by adrianbj** [comment]
Does maybe https://github.com/flydev-fr/Duplicator/blob/master/Duplicator.module#L604 need to return false?
