### ISSUE TITLE
null count error

### ISSUE THREAD

**Issue by adrianbj** [flydev-fr/Duplicator#49]
Hi @flydev-fr - I had to add change https://github.com/flydev-fr/Duplicator/blob/e4ab48fac2e43d0668e2fb7cbc90f3c3b9fb2cd0/ProcessDuplicator.module#L463 to 

```
if ($files && count($files)) {
```

to avoid an error when first configuring S3 backups (and before the first one was created), otherwise I got a fatal error when going to Setup > Duplicator.

**Comment by flydev-fr** [comment]
Good catch thanks @adrianbj
